services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${DB_SQL_CONTAINER_NAME}
    hostname: ${DB_SQL_HOST}
    ports:
      - "${DB_SQL_PORT}:1433"
    environment:
      # Basic Configuration
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_SQL_PASSWORD}
      MSSQL_PID: Express
      MSSQL_ENCRYPT: "true"
      MSSQL_TRUST_CERT: "true"
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist SQL Server data
      - ./DatabaseScript/SQLServer/Sqls:/scripts # Bind mount for SQL scripts
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q ''SELECT @@SERVERNAME, @@VERSION, SERVERPROPERTY("Edition")'' -C -b -t 30 -v TRUST=''TrustServerCertificate=yes''',
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer:latest
    container_name: ${ADMINER_CONTAINER_NAME}
    hostname: ${ADMINER_HOST}
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
      ADMINER_DESIGN: "pepa-linha-dark"
    depends_on:
      - sqlserver
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBIT_CONTAINER_NAME}
    hostname: ${RABBIT_HOST}
    ports:
      - "${RABBIT_PORT}:5672" # AMQP protocol port
      - "${RABBIT_MANAGEMENT_PORT}:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    restart: unless-stopped

  redis:
    image: "redis:latest"
    container_name: ${REDIS_CONTAINER_NAME}
    hostname: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  sqlserver_data:
  rabbitmq_data:
  rabbitmq_log:
  redis_data:
